### ISSUE TITLE
Bug with increments

### ISSUE THREAD

**Issue by hlozancic** [adonisjs/lucid-slugify#12]
Increment strategy is not working as expected sometimes.

Try creating 3 slugs with title *test*.
Slugs generated will be: test, test-1, test-2

Now go inside database and update slug test-2 to test-5.

Next time you create test, test-6 will be generated.

Now, update test-6 to test-3, and continue creating test titles. It will throw DUPLICATE ENTRY test-5 FOR key xxx_slug_unique when it hits slug 5 again, as it start to count from last entry.

**Comment by thetutlage** [comment]
Fixed in next rewrite for v5
