### ISSUE TITLE
Generate a slug from multiple fields

### ISSUE THREAD

**Issue by olaoluwa-98** [adonisjs/lucid-slugify#13]
It would be nice if this package is able to take more than one field to generate a slug. For example, imagine a database table that has a combination of columns as unique, it would be nice that this package can take those columns as input to generate a slug.

**Comment by Enethion** [comment]
I agree with that. While I can create slug based on two fields (`title` and `published_at`) and it will update when I change the title, it is impossible to force update for changed `published_at` value. Or at least I can't find the proper way.

**Comment by olaoluwa-98** [comment]
@thetutlage can I open a PR for this?

**Comment by techwebdev** [comment]
@olaoluwa-98 I agree with you because when generate using the city, state, a country then I face this difficulty. I try to find a way but can't get a proper answer so I generate custom function for generating a slug

**Comment by thetutlage** [comment]
Fixed in next rewrite for v5
