### ISSUE TITLE
Add unique by fields possibility

### ISSUE THREAD

**Issue by yariksav** [adonisjs/lucid-slugify#17]
It would be great to add some unique by fields property, to add the same slug ability for different fields

For example, I have one table *terms* for different sites, and each site can have slug 'test'

```sql
CREATE TABLE terms (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    site_id uuid REFERENCES sites(id) ON DELETE CASCADE,
    name character varying(255) NOT NULL,
    slug character varying(255)
);
```
And

```
  @slugify({
    strategy: 'dbIncrement',
    fields: ['name'],
    uniqueByFields: ['siteId'], // <---
    allowUpdates: true,
    maxLength: 64
  })
  @column()
  public slug: string
```

Thank you for your awesome work!

**Comment by yariksav** [comment]
No chance?

**Comment by thetutlage** [comment]
Hey! Sorry for the late reply. I wasn't watching this repo somehow.

I am not sure if I understand the request properly. Did you mean, you want to prefix a value to the slug?

**Comment by yariksav** [comment]
Hi, @thetutlage, no, i mean slug can be unique only in one (or many) field, for example siteId/
For example this is correct same slugs

| id | title | siteId  | slug |
| ----- | ---- | ---- | ---- |
| 1  | Test title | 1 | test_title  |
| 2 | Test title | 2 | test_title  |

**Comment by thetutlage** [comment]
This is something outside the scope of this package. I will try to keep things simple for now

**Comment by yariksav** [comment]
Thank you, I hope you will find a time and mood for this enhancement ;)

**Comment by thetutlage** [comment]
Closing it for now. Feel free to reopen if you plan to contribute a PR :)
