### ISSUE TITLE
Feature request: dbIncrement strategy with "where" clause for multi-tenant applications

### ISSUE THREAD

**Issue by joelcieslar** [adonisjs/lucid-slugify#19]
## Why this feature is required (specific use-cases will be appreciated)?
I am building a multi-tenant application which uses a shared database.

It was my preference to use the `dbIncrement` strategy, with the slugs being unique _per tenant_, rather than per table.

Currently, we use the `dbIncrement` strategy like this:

```ts
 @column()
 @slugify({
    strategy: 'dbIncrement',
    fields: ['title']
 })
 public slug: string
```

The `@adonisjs/validator` package has a `rules.unique()` method which can accept a `where` clause. The [example in the docs](https://docs.adonisjs.com/reference/validator/rules/unique#additional-constraints) uses multi-tenancy as a use case.

It would be great if the `dbIncrement` slugify strategy could be used in the same way:

```ts
 @column()
 @slugify({
    strategy: 'dbIncrement',
    fields: ['title'],
    where: {
        tenantId: '1'
    }
 })
 public slug: string
```

In my use case, all tenants will add roughly the same type of data to the application (let's say, place names) so making slugs unique on a per-table basis (as opposed to per-tenant) wouldn't really be feasible. It would result in something like `london`, `london-1` ... `london-49` ... `london-291` ... `london-64993`, etc.

## Have you tried any other work arounds?
It would be possible to achieve this using a custom strategy, but I think multi-tenancy is a common use case, therefore it would be great if this could work out of the box.

**Comment by thetutlage** [comment]
> but I think multi-tenancy is a common use case

Yup, but I usually keep things unique across the entire tables vs per tenant. I do it same for email addresses as well.

So for now, I will recommend creating a custom strategy.

**Comment by thetutlage** [comment]
Closing since not actionable
