### ISSUE TITLE
Error "sqlMessage": "FUNCTION database.REGEXP_SUBSTR does not exist",

### ISSUE THREAD

**Issue by petronioamaral** [adonisjs/lucid-slugify#21]
Hello there,

When I tried create a new row I got this error.

`
{
	"code": "ER_SP_DOES_NOT_EXIST",
	"errno": 1305,
	"sqlState": "42000",
	"sqlMessage": "FUNCTION database.REGEXP_SUBSTR does not exist",
	"sql": "select CAST(REGEXP_SUBSTR(slug, '[0-9]+$') AS UNSIGNED) as lucid_slugify_counter from `adverts` where `slug` REGEXP '^iphone-celular-12(-[0-9]*)?$' order by `lucid_slugify_counter` desc"
}
`

I added in my model

`import { BaseModel, column, decimal, BelongsTo, belongsTo, text, HasMany, hasMany } from '@ioc:Adonis/Lucid/Orm'
import { slugify } from '@ioc:Adonis/Addons/LucidSlugify'`

`@column()
  @slugify({
    strategy: 'dbIncrement',
    fields: ['title'],
  })
  public slug: string
`
`  @column()
  public title: string`

` const data = await Advert.create({ title, price, description  })`

package.json
`  "devDependencies": {
    "@adonisjs/assembler": "^5.8.1",
    "@japa/preset-adonis": "^1.2.0",
    "@japa/runner": "^2.2.1",
    "adonis-preset-ts": "^2.1.0",
    "eslint": "^8.23.1",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-adonis": "^2.1.0",
    "eslint-plugin-prettier": "^4.2.1",
    "pino-pretty": "^9.1.0",
    "prettier": "^2.7.1",
    "typescript": "~4.6",
    "youch": "^3.2.2",
    "youch-terminal": "^2.1.5"
  },
  "dependencies": {
    "@adonisjs/core": "^5.8.0",
    "@adonisjs/lucid": "^18.1.1",
    "@adonisjs/lucid-slugify": "^2.2.1",
    "@adonisjs/repl": "^3.1.0",
    "luxon": "^3.0.3",
    "mysql": "^2.18.1",
    "mysql2": "^2.3.3",
    "openapi-types": "^12.0.2",
    "proxy-addr": "^2.0.7",
    "reflect-metadata": "^0.1.13",
    "sharp": "^0.31.1",
    "source-map-support": "^0.5.21"
  }`

## Node.js and npm version
v16.17.0

**Comment by RomainLanz** [comment]
Hey @petronioamaral! 👋🏻 

What database are you using?

**Comment by petronioamaral** [comment]
> Hey @petronioamaral! 👋🏻
> 
> What database are you using?

Hello @RomainLanz , mysql 5.7.26

**Comment by RomainLanz** [comment]
The `REGEXP_SUBSTR` function does not exist in MySQL 5.7. Update to version 8.

**Comment by thetutlage** [comment]
Or, you will have to specify the MySQL version in the config file for this package to know which version you are using.

```ts
{
  client: 'mysql', // or mysql2
  version: '5.7'
}
```
