### ISSUE TITLE
generate slug only if it is not sent through the request from client-side

### ISSUE THREAD

**Issue by thau0x01** [adonisjs/lucid-slugify#9]
Hello Virk, how are you?

I have a simple question about this package, can i create the slug based on a model field, only if the slug value is not present on the request or if its not set when creating the model?

**Comment by RomainLanz** [comment]
Hey @NeroOficial! 👋 

We need to change a little bit the code to make it work like that.

When we generate the slug, we need to verify that the slug isn't already defined.

The verification should be around [those lines](https://github.com/adonisjs/adonis-lucid-slugify/blob/develop/src/Slugify/index.js#L54).

We would be happy to accept a PR. 🤗

**Comment by NeroOficial** [comment]
@RomainLanz  wow, amazing, just forking to do this in the next weekend.

**Comment by NeroOficial** [comment]
@RomainLanz just sent the PR #10

**Comment by NeroOficial** [comment]
@RomainLanz, @thetutlage  any updates?

**Comment by yariksav** [comment]
Need this changes too

**Comment by RomainLanz** [comment]
I'll take a look this weekend!

**Comment by thetutlage** [comment]
Added support for this in next rewrite for v5
